repos:
  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.32.0
    hooks:
      - id: yapf
        args: [--in-place, --parallel, --recursive, --style, .yapf-config]
        exclude: "(oscal|third_party)"
        stages: [commit]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args: [--extend-ignore, "P1,C812,C813,C814,C815,C816,W503,W605"]
        additional_dependencies:
          [
            flake8-2020,
            flake8-broken-line,
            flake8-bugbear,
            flake8-builtins,
            flake8-commas,
            flake8-comprehensions,
            flake8-docstrings,
            flake8-eradicate,
            flake8-import-order,
            flake8-mutable,
            flake8-pep3101,
            flake8-print,
            flake8-quotes,
            flake8-string-format,
            flake8-use-fstring,
            pep8-naming,
          ]
        exclude: "(oscal|third_party)"
        stages: [commit]
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.14 # Do not change version. 0.6.0 introduces breaking changes.
    hooks:
    - id: mdformat
      exclude: "CHANGELOG.md|docs/mkdocs_code_of_conduct.md|docs/api_reference|tests/data/md"
      additional_dependencies:
      - mdformat-tables
      - mdformat-config
      - mdformat-frontmatter
